Repository Netcracker/qubership-integration-variables-management, pull requests merged in 2025-07, with the labels that each got.

#50 Added development mode for secured variables
  pom.xml
  src/main/java/org/qubership/integration/platform/variables/management/configuration/KubeOperatorAutoConfiguration.java
  src/main/java/org/qubership/integration/platform/variables/management/kubernetes/DefaultKubeOperator.java
  src/main/java/org/qubership/integration/platform/variables/management/kubernetes/KubeOperator.java
  src/main/java/org/qubership/integration/platform/variables/management/kubernetes/LocalDevKubeOperator.java
  src/main/java/org/qubership/integration/platform/variables/management/persistence/configs/entity/actionlog/ActionLog.java
  src/main/java/org/qubership/integration/platform/variables/management/rest/exception/SecretNotFoundException.java
  src/main/java/org/qubership/integration/platform/variables/management/rest/v2/controller/SecretControllerV2.java
  src/main/java/org/qubership/integration/platform/variables/management/rest/v2/mapper/SecretResponseMapper.java
  src/main/java/org/qubership/integration/platform/variables/management/service/ActionsLogService.java
  src/main/java/org/qubership/integration/platform/variables/management/service/DefaultVariablesService.java
  src/main/java/org/qubership/integration/platform/variables/management/service/SecretNameResolverService.java
  src/main/java/org/qubership/integration/platform/variables/management/service/SecretService.java
  src/main/java/org/qubership/integration/platform/variables/management/service/SecuredVariableService.java
  src/main/java/org/qubership/integration/platform/variables/management/service/secrets/K8sSecretService.java
  src/main/java/org/qubership/integration/platform/variables/management/service/secrets/SecretService.java
  src/main/resources/application-development.yml
  src/test/java/org/qubership/integration/platform/variables/management/service/SecuredVariablesServiceTest.java
  src/test/java/org/qubership/integration/platform/variables/management/service/secrets/K8sSecretServiceTest.java
Labels: bug

#55 [0.1] feat: Updated spring lib versions
  pom.xml
Labels: feature

#52 fix: #51 Import common variables zip archive
  .gitignore
  src/main/java/org/qubership/integration/platform/variables/management/service/CommonVariablesService.java
  src/main/java/org/qubership/integration/platform/variables/management/util/ExportImportUtils.java
Labels: bug

#58 fix: [0.1] #57 Fixed the STARTS_WITH condition for filter
  src/main/java/org/qubership/integration/platform/variables/management/persistence/configs/entity/enums/filter/FilterCondition.java
  src/main/java/org/qubership/integration/platform/variables/management/persistence/configs/repository/actionlog/ActionLogFilterRepositoryImpl.java
  src/main/java/org/qubership/integration/platform/variables/management/service/exportimport/instructions/filter/ImportInstructionsFilterSpecificationBuilder.java
Labels: bug

#59 fix: #57 Fixed the STARTS_WITH condition for filter
  src/main/java/org/qubership/integration/platform/variables/management/persistence/configs/entity/enums/filter/FilterCondition.java
  src/main/java/org/qubership/integration/platform/variables/management/persistence/configs/repository/actionlog/ActionLogFilterRepositoryImpl.java
  src/main/java/org/qubership/integration/platform/variables/management/service/exportimport/instructions/filter/ImportInstructionsFilterSpecificationBuilder.java
Labels: bug

#60 feat: Updated spring lib versions
  pom.xml
Labels: enhancement, feature
